### ISSUE TITLE
Improve blockquote contrast on dark theme

### ISSUE THREAD

**Issue by Lange** [nodecg/docs#22]
Currently looks like this (screenshot taken from a page I'm working on which is not in the repo yet):

![image](https://user-images.githubusercontent.com/873012/76170745-d101f380-6152-11ea-8a95-3b0bb091499f.png)

**Comment by EwanLyon** [comment]
Fixed in 9affca8. Gave it a lighter grey to make to AAA contrast.
Also fixed alert/admonition colours that broke in the new version of docusaurus.
