### ISSUE TITLE
Ensure WCAG AAA contrast standards are met on all pages in both themes

### ISSUE THREAD

**Issue by Lange** [nodecg/docs#4]
Right now, the light theme has contrast issues with the teal color:

![image](https://user-images.githubusercontent.com/873012/75576914-7a940700-5a26-11ea-85eb-5b23c61402c2.png)

![image](https://user-images.githubusercontent.com/873012/75576910-78ca4380-5a26-11ea-8c79-8cb0e2754deb.png)

**Comment by Lange** [comment]
We may want to consider running an accessibility check as part of our CI/build process. I think Lighthouse can do accessibility audits now.

**Comment by EwanLyon** [comment]
Made wcag-aaa branch that could solve this but I want to merge it with the azure-pipelines branch to fully test everything. Most admonition colours will have to change to hit AAA certification though.

**Comment by Lange** [comment]
Feel free to commit directly to the azure-pipelines branch

**Comment by Lange** [comment]
Fixed by #18
